#! /usr/bin/env python
# encoding: utf-8

def options(opt):
	pass

def configure(conf):
	conf.load('gas')

	conf.env.append_value('CFLAGS', '-msse4.1')
	conf.env.append_value('OBJ', 'io')

def build(bld):
	bld(
		source = 'io.s',
		features = 'asm',
		target = 'io')
	pass
