#! /usr/bin/env python
# encoding: utf-8

def options(opt):
	pass

def configure(conf):
	conf.env.append_value('CFLAGS', '-msse4.1')

	conf.env.append_value('OBJ', 'io')

def build(bld):
	"""
	bld.objects(
		source = 'io.s',
		features = 'c',
		target = 'io')
	"""
